[0m11:44:15.895407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107409690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076867d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107a03210>]}


============================== 11:44:15.897761 | ced2acd7-30b8-409b-a6f2-e961b59feef0 ==============================
[0m11:44:15.897761 [info ] [MainThread]: Running with dbt=1.7.6
[0m11:44:15.898093 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/nicolascorchuelo/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:44:15.898446 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/nicolascorchuelo/.dbt')}
[0m11:44:15.898640 [info ] [MainThread]: Creating dbt configuration folder at 
[0m11:45:12.069950 [debug] [MainThread]: Starter project path: /Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/dbt/include/starter_project
[0m11:45:12.086453 [info ] [MainThread]: 
Your new dbt project "load_snowflake" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:45:12.088698 [info ] [MainThread]: Setting up your profile.
[0m11:45:14.736555 [error] [MainThread]: Encountered an error:

[0m11:45:14.744253 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/dbt/cli/requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/dbt/cli/requires.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "/Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/dbt/task/init.py", line 344, in run
    self.setup_profile(profile_name)
  File "/Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/dbt/task/init.py", line 263, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/dbt/task/init.py", line 244, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolascorchuelo/Documents/projects/portfolio/languages_programming/python/python_for_data/elt_dbt/elt_dbt/lib/python3.11/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m11:45:14.771825 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 58.88485, "process_user_time": 0.743345, "process_kernel_time": 0.130499, "process_mem_max_rss": "111099904", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:45:14.772350 [debug] [MainThread]: Command `dbt init` failed at 11:45:14.772251 after 58.89 seconds
[0m11:45:14.772701 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107a0fdd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073c7b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107a00d10>]}
[0m11:45:14.773051 [debug] [MainThread]: Flushing usage events
